# MainRobot:
#   module: Panda2LIRMMDefault::BoneTag::Femur
#   name: panda_femur
MainRobot:
  #module: Panda2LIRMM_2::Default::BoneTag::Femur
  module: Panda2LIRMM_FR1_Default_Table2_Calibrated::TKA::Femur
  name: panda_femur

# MainRobot:
#   module: Panda2LIRMMDefault::TAA::Tibia
#   name: panda_femur

# MainRobot:
#   module: Panda2LIRMMDefault::TSA::Glenoid
#   name: panda_femur

# MainRobot:
#   module: Panda7LIRMMDefault::TSA::Humerus
#   name: panda_tibia

# MainRobot: UR10::BoneTag::Femur
Enabled: PandaProsthesis
Timestep: 0.001
Log: true

# Franka specific configuration
Franka:
  ShowNetworkWarnings: false # If true (default), show warning messages about missing network data
  ControlMode: Velocity # Can be: Position/Velocity/Torque
  #ControlMode: Position # Can be: Position/Velocity/Torque
  panda_femur: # Robot on which the femur (positive knee) is attached
    ip: panda2 # IP of the robot
  panda_tibia: # Robot on which the tibia is attached
    ip: panda7
  # Actuated robots that are not controlled via mc_franka
  ignored: [env/door, env/box]

ControllerModulePaths: ["/home/nixos/workspace/install/lib64/mc_controller"]
RobotModulePaths: ["/home/nixos/workspace/install/lib64/mc_robots", "/nix/store/3p0p4zjxafy7svlpj9cfxjl7v0vj645k-mc-panda-lirmm-1.0.0/lib64/mc_robots", "/nix/store/3p0p4zjxafy7svlpj9cfxjl7v0vj645k-mc-panda-lirmm-1.0.0/lib/mc_robots", "/nix/store/kfflhqbhxpvynsn2kw6wlfp5j4hpj5m6-mc-panda-1.0.0/lib64/mc_robots", "/nix/store/kfflhqbhxpvynsn2kw6wlfp5j4hpj5m6-mc-panda-1.0.0/lib/mc_robots"]
ObserverModulePaths: ["/home/nixos/workspace/install/lib64/mc_observers", "/nix/store/mi2203954la10a6v1ys4njq9bijc2pw7-mc-state-observation-1.1.0/lib64/mc_observers", "/nix/store/mi2203954la10a6v1ys4njq9bijc2pw7-mc-state-observation-1.1.0/lib/mc_observers"]
GlobalPluginPaths: ["/home/nixos/workspace/install/lib64/mc_plugins"]